### ISSUE TITLE
Zebble Framework Template is not in project template list 

### ISSUE THREAD

**Issue by abolfazlrezaeiv** [Geeksltd/Zebble.Docs#1]
Hello ,

Zebble Framework Template is not in the project template list when I try to make a new project in vs 2019
I followed all steps in tutorial but nothing has changed

**Comment by m-sadegh-sh** [comment]
Hi @abolfazl2643,

Sorry for the out-dated docs, please refer to [zebble-build](https://www.nuget.org/packages/zebble-build) CLI as we've changed the way we create Zebble projects. After you've installed the CLI, use the following command to create an empty Zebble project.

`zebble-build new --name MyZebbleApp1`

**Comment by abolfazlrezaeiv** [comment]
Thank you,
You are a lifesaver, After 2 days of playing with plugins now, I have a real Zebble project open!
Now I have a new problem , When I open "READ-ME-NOW!!!.TXT" it says that I must run a file called "RUN-ME-now!!!!!.BAT" but I looked everywhere in the file tree and there isn't any file like that 
what can I do now?

**Comment by m-sadegh-sh** [comment]
@abolfazl2643 Ignore that file as the instructions are not required anymore.
